// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(function($) {
    var app;
    app = {
      init: function() {
        return this.fancybox();
      },
      fancybox: function() {
        if ($.fancybox) {
          return $('.fancybox').click(function() {
            return $('.fancybox').fancybox({
              href: $(this).data('section'),
              minWidth: 445,
              width: 445,
              padding: 0,
              helpers: {
                overlay: {
                  css: {
                    'background': 'rgba(245, 245, 245, .85)'
                  }
                }
              }
            });
          });
        }
      }
    };
    return app.init();
  });

}).call(this);
